### ISSUE TITLE
Cannot modify files created under my username

### ISSUE THREAD

**Issue by sebm253** [TopiSenpai/godrive#7]
When trying to edit/delete files with my username as the owner, I get an error attached below. Ironically, I'm able to modify files which have "Unknown" as their owner. I'm not sure whether this is a problem specific to my user, but I created this issue just for tracking purposes.

![image](https://github.com/topi314/godrive/assets/42180891/ff97ab88-855d-4aee-8095-44def6346f3d)

**Comment by topi314** [comment]
fixed in https://github.com/topi314/godrive/commit/c09c885a885800e1d0b1dfba4f0a475d173631c3
